version: '3.5'
services:
    nginx:
        build: ./docker/images/nginx
        ports:
            - "8090:80"
            # - "443:443"
        volumes:
            - ./docker/images/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./application:/var/www/html
            - ./logs:/var/log/nginx
            - ./letsencrypt:/etc/letsencrypt
            - ./acme-challenge:/var/lib/certbot/.well-known/acme-challenge
        links:
            - app

    app:
        build: ./docker/images/php80
        working_dir: /var/www/html
        links:
            - postgresql
        volumes:
            - ./application:/var/www/html
            - ./docker/images/php80/php.ini:/usr/local/etc/php/conf.d/php.ini
    
    postgresql:
        image: postgres:9.6.21-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: jdasfjn123HJSD
            POSTGRES_DB: gigant-panel
        restart: always

